const actionType = Object.freeze({
  CHECK_LOGIN_SUCCESS: "CHECK_LOGIN_SUCCESS",
  CHECK_LOGIN_FAIL: "CHECK_LOGIN_FAIL",
  SHOW_MODAL_EDIT_USER: "SHOW_MODAL_EDIT_USER",
  SHOW_MODAL_DETAIL_USER: "SHOW_MODAL_DETAIL_USER",
  SHOW_MODAL_EDIT_PACKAGE: "SHOW_MODAL_EDIT_PACKAGE",
  SHOW_MODAL_DETAIL_PACKAGE: "SHOW_MODAL_DETAIL_PACKAGE",
  GET_ALL_USER_SUCCESS: "GET_ALL_USER_SUCCESS",
  GET_ALL_USER_FAIL: "GET_ALL_USER_FAIL",
  GET_USER_BY_ID_SUCCESS: "GET_USER_BY_ID_SUCCESS",
  GET_USER_BY_ID__FAIL: "GET_USER_BY_ID__FAIL",
  EDIT_USER_BY_ID_SUCCESS: "EDIT_USER_BY_ID_SUCCESS",
  EDIT_USER_BY_ID__FAIL: "EDIT_USER_BY_ID__FAIL",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
});
export default actionType;
